<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerN35nxhg\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerN35nxhg/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerN35nxhg.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerN35nxhg\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerN35nxhg\appProdProjectContainer([
    'container.build_hash' => 'N35nxhg',
    'container.build_id' => '0919d5b9',
    'container.build_time' => 1549801920,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerN35nxhg');
